[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_demo = "85FPqMxy9QEeq5ejVMkuWYHsX8X6eTwqfaEe6hvTMcGS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/akash/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
